/**
 * Self-test firmware generator — public API.
 *
 * Imports all probes, filters by board, composes firmware files.
 * To add a test: create a new probe in probes/ and add it to ALL_PROBES below.
 */

import type { BoardDef } from '../board.js';
import type { GeneratedFile, SecretsMap } from '../generate.js';
import type { NetworkConfig } from '@far-mon/core';
import type { TestProbe } from './probe.js';
import { generateBoardPackage } from '../generators/board-package.js';
import { generateSequencer } from './sequencer.js';
import { generateDeviceYaml } from './device-yaml.js';
import { generateDashboard } from './dashboard.js';
import * as crypto from 'node:crypto';

// --- Probe registry (add new probes here) ---
import { i2cScanProbe } from './probes/i2c-scan.js';
import { relayCycleProbe } from './probes/relay-cycle.js';
import { digitalInputsProbe } from './probes/digital-inputs.js';
import { adcBaselineProbe } from './probes/adc-baseline.js';
import { sensorHeadersProbe } from './probes/sensor-headers.js';
import { ethernetPhyProbe } from './probes/ethernet-phy.js';
import { oledDisplayProbe } from './probes/oled-display.js';
import { loraSpiProbe } from './probes/lora-spi.js';
import { wifiScanProbe } from './probes/wifi-scan.js';
import { batteryAdcProbe } from './probes/battery-adc.js';
import { ledBlinkProbe } from './probes/led-blink.js';
import { vextGateProbe } from './probes/vext-gate.js';

const ALL_PROBES: TestProbe[] = [
  i2cScanProbe,
  relayCycleProbe,
  digitalInputsProbe,
  adcBaselineProbe,
  sensorHeadersProbe,
  ethernetPhyProbe,
  oledDisplayProbe,
  loraSpiProbe,
  wifiScanProbe,
  batteryAdcProbe,
  ledBlinkProbe,
  vextGateProbe,
];

/** Filter probes to those applicable for a board. */
export function activeProbes(board: BoardDef): TestProbe[] {
  return ALL_PROBES.filter(p => p.appliesTo(board));
}

function generateSecrets(secrets?: SecretsMap): string {
  const s = secrets ?? {
    wifi_ssid: '',
    wifi_password: '',
    fallback_password: crypto.randomBytes(16).toString('hex'),
    api_key: crypto.randomBytes(32).toString('base64'),
    ota_password: crypto.randomBytes(16).toString('hex'),
  };
  return [
    `# Self-test secrets`,
    `# Generated by MajiFlow`,
    ``,
    `wifi_ssid: "${s.wifi_ssid}"`,
    `wifi_password: "${s.wifi_password}"`,
    `fallback_password: "${s.fallback_password}"`,
    `api_key: "${s.api_key}"`,
    `ota_password: "${s.ota_password}"`,
    ``,
  ].join('\n');
}

/** Generate all files for self-test firmware. */
export function generateSelfTest(board: BoardDef, secrets?: SecretsMap, network?: NetworkConfig): GeneratedFile[] {
  const model = board.model.replace('_', '-');
  const dir = `selftest-${model}`;
  const probes = activeProbes(board);

  return [
    {
      relativePath: `esphome/${dir}/common/board.yaml`,
      description: `${board.label} board package (buses, networking, diagnostics)`,
      content: generateBoardPackage(board, network),
    },
    {
      relativePath: `esphome/${dir}/${dir}.yaml`,
      description: `Self-test device config (${probes.length} probes)`,
      content: generateDeviceYaml(board, probes),
    },
    {
      relativePath: `esphome/${dir}/packages/self-test.h`,
      description: `C++ test sequencer (${probes.length} test phases)`,
      content: generateSequencer(board, probes),
    },
    {
      relativePath: `esphome/${dir}/secrets.yaml`,
      description: 'WiFi + API credentials',
      content: generateSecrets(secrets),
    },
    {
      relativePath: `config/homeassistant/dashboards/${dir}.yaml`,
      description: `HA dashboard for self-test results`,
      content: generateDashboard(board, probes),
    },
  ];
}
