# See https://www.chirpstack.io/docs/chirpstack-gateway-bridge/configuration.html

[integration.mqtt]
  [integration.mqtt.auth]
    type = "generic"

    [integration.mqtt.auth.generic]
      servers = ["tcp://mosquitto:1883/"]

[backend]
  type = "semtech_udp"

  [backend.semtech_udp]
    udp_bind = "0.0.0.0:1700"
