import type { Manifest } from '@core';
import type { BoardDef, ExpansionBoardCatalog } from '@core';
import { generateRoutes } from "./generators/routes";
import { generateHardware } from "./generators/hardware";
import { generateSensors } from "./generators/sensors";
import { generateBoardPackage } from "./generators/board-package";
import { generateDeviceYaml } from "./generators/device-yaml";
import { generateControl } from "./generators/control";
import { generateMqtt } from "./generators/mqtt";
import { generateAutomationEngineHeader, generateAutomationEngineYaml } from "./generators/automation-engine";
import { generateCoordination, generateCoordinationHeader } from "./generators/coordination";
import { generateTimeSync, generateTimeSyncHeader } from "./generators/time-sync";

import { collectEntityCodegen } from "./generators/collect";
import { LOGO_SVG } from '@core';
import { type GeneratorId, type SecretsMap, type GenerationMetadata } from './backends/types';

export interface GeneratedFile {
  relativePath: string;
  description: string;
  content: string;
}

export { type GeneratorId, type SecretsMap, type GenerationMetadata } from './backends/types';

/** Convenience helper for tests — creates a valid GenerationMetadata with defaults. */
export function createTestMetadata(overrides?: Partial<GenerationMetadata>): GenerationMetadata {
  return {
    configSha: 'testsha000000000',
    version: 'testver1',
    siteId: 'test-site',
    controllerId: 'default',
    schemaVersion: 16,
    buildTimestamp: 0,
    appVersion: '0.0.0',
    mode: 'managed',
    brokerAddress: '127.0.0.1',
    brokerPort: 1883,
    brokerTls: false,
    brokerCa: '',
    ...overrides,
  };
}

/** Cryptographically-random bytes via Web Crypto (browser + Node 19+). */
function randomBytes(n: number): Uint8Array {
  const b = new Uint8Array(n);
  globalThis.crypto.getRandomValues(b);
  return b;
}

function toBase64(bytes: Uint8Array): string {
  let s = '';
  for (const byte of bytes) s += String.fromCharCode(byte);
  return btoa(s);
}

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

export function generateDefaultSecrets(): SecretsMap {
  return {
    ota_password: toHex(randomBytes(16)),
    mqtt_token: toBase64(randomBytes(32)),
    udp_key: toHex(randomBytes(32)),
  };
}

function generateSecretsYaml(m: Manifest, secrets?: SecretsMap): string {
  const s = secrets ?? generateDefaultSecrets();
  return [
    `# ESPHome secrets for ${m.device.friendly_name}`,
    `# Generated by MajiFlow. Wifi is NOT here — it is provisioned on the device`,
    `# (captive portal / improv) and stored in its own flash (NVS).`,
    ``,
    `ota_password: "${s.ota_password}"`,
    `mqtt_token: "${s.mqtt_token}"`,
    `udp_key: "${s.udp_key}"`,
    ``,
  ].join("\n");
}

function generateMetadataYaml(m: Manifest, metadata: GenerationMetadata): string {

  const lines: string[] = [];
  lines.push(`# =============================================================================`);
  lines.push(`# MajiFlow — Fleet Metadata Sensors`);
  lines.push(`# =============================================================================`);
  lines.push(`# Embedded provenance for drift detection and fleet management.`);
  lines.push(`# These sensors publish to Home Assistant as diagnostic entities.`);
  lines.push(`# =============================================================================`);
  lines.push(``);

  // text_sensor block
  lines.push(`text_sensor:`);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_config_sha`);
  lines.push(`    name: "MajiFlow Config SHA"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.configSha}";`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_generation_version`);
  lines.push(`    name: "MajiFlow Generation"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.version}";`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_site_id`);
  lines.push(`    name: "MajiFlow Site"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.siteId}";`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_controller_id`);
  lines.push(`    name: "MajiFlow Controller"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.controllerId}";`);
  lines.push(``);

  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_device_name`);
  lines.push(`    name: "MajiFlow Device Name"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${m.device.name}";`);
  lines.push(``);

  // sensor block
  lines.push(`sensor:`);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_build_timestamp`);
  lines.push(`    name: "MajiFlow Build Time"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    unit_of_measurement: "timestamp"`);
  lines.push(`    lambda: return ${metadata.buildTimestamp};`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_schema_version`);
  lines.push(`    name: "MajiFlow Schema"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return ${metadata.schemaVersion};`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_route_count`);
  lines.push(`    name: "MajiFlow Routes"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return ${m.routes.length};`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_node_count`);
  lines.push(`    name: "MajiFlow Nodes"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return ${m.nodes.length};`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Returns the relative path prefix for everything a site generates.
 * `sites/{siteId}/...` is the single root for site-scoped artifacts:
 *   - `esphome/{deviceDir}/...`     — ESPHome firmware
 *   - `homeassistant/dashboards/{siteId}.yaml`        — site dashboard
 *   - `homeassistant/dashboards/dashboard.yaml`       — single-system convenience (tests)
 *   - `homeassistant/automations/{deviceDir}.yaml`    — per-device automations
 *   - `homeassistant/www/farm/{name}.{svg,meta.json}` — SCADA artifacts
 *   - `site-documentation.html`                       — generated docs
 *
 * Self-test artifacts live in a separate `selftest/{model}/` tree and bypass
 * this prefix entirely — they are not site-scoped.
 */
export function siteRoot(siteId: string): string {
  return `sites/${siteId}`;
}

export function generateEsphome(
  m: Manifest,
  board: BoardDef,
  siteId: string,
  secrets: SecretsMap | undefined,
  metadata: GenerationMetadata,
  expansionBoards: ExpansionBoardCatalog,
): GeneratedFile[] {
  const dir = m.device.directory ?? m.device.name;
  const deviceDir = `${siteRoot(siteId)}/esphome/${dir}`;
  const collected = collectEntityCodegen(m, board, expansionBoards, metadata);

  const files: GeneratedFile[] = [
    {
      relativePath: `${deviceDir}/common/board.yaml`,
      description: `${board.label} board package (buses, battery, LED, diagnostics)`,
      content: generateBoardPackage(board, m.device.network),
    },
    {
      relativePath: `${deviceDir}/common/images/logo.svg`,
      description: "Logo image for OLED splash screen",
      content: LOGO_SVG,
    },
    {
      relativePath: `${deviceDir}/${dir}.yaml`,
      description: "Device config (substitutions, boot, OLED display)",
      content: generateDeviceYaml(board, m, collected, metadata),
    },
    {
      relativePath: `${deviceDir}/secrets.yaml`,
      description: "WiFi + OTA credentials",
      content: generateSecretsYaml(m, secrets),
    },
    {
      relativePath: `${deviceDir}/packages/control.yaml`,
      description: "State machine + safety watchdog",
      content: generateControl(m),
    },
    {
      relativePath: `${deviceDir}/packages/mqtt.yaml`,
      description: "MQTT runtime: telemetry publish, command subscribe, status",
      content: generateMqtt(m, metadata, board),
    },
    {
      relativePath: `${deviceDir}/packages/routes.h`,
      description: "C++ route table + dispatch functions",
      content: generateRoutes(m),
    },
    {
      relativePath: `${deviceDir}/packages/automation-engine.h`,
      description: "C++ runtime automation table + generic trigger evaluator",
      content: generateAutomationEngineHeader(m),
    },
    {
      relativePath: `${deviceDir}/packages/automation-engine.yaml`,
      description: "Runtime automation engine: 5s evaluator interval",
      content: generateAutomationEngineYaml(),
    },
    {
      relativePath: `${deviceDir}/packages/coordination.h`,
      description: "C++ cross-controller coordination (UDP HMAC, message build/parse, dispatcher)",
      content: generateCoordinationHeader(m, metadata),
    },
    {
      relativePath: `${deviceDir}/packages/coordination.yaml`,
      description: "Cross-controller coordination over UDP (udp: block, on_receive, reading broadcast)",
      content: generateCoordination(m),
    },
    {
      relativePath: `${deviceDir}/packages/time-sync.h`,
      description: "C++ persisted-clock boot seed (no-RTC time across reboots)",
      content: generateTimeSyncHeader(metadata),
    },
    {
      relativePath: `${deviceDir}/packages/time-sync.yaml`,
      description: "Persisted wall clock: flash-restored epoch + refresh interval",
      content: generateTimeSync(),
    },
    {
      relativePath: `${deviceDir}/packages/hardware.yaml`,
      description: "Pump relay, valve switches + covers",
      content: generateHardware(m, collected),
    },
    {
      relativePath: `${deviceDir}/packages/sensors.yaml`,
      description: "Flow sensors, tank levels, calibration, state text",
      content: generateSensors(m, collected),
    },
    {
      relativePath: `${deviceDir}/packages/metadata.yaml`,
      description: "Fleet metadata sensors (SHA, version, build timestamp)",
      content: generateMetadataYaml(m, metadata),
    },
    {
      relativePath: `${deviceDir}/compile.sh`,
      description: "One-shot helper: compile / flash / tail logs via ESPHome",
      content: generateCompileScript(dir),
    },
  ];

  return files;
}

/**
 * Emits a self-contained helper script placed alongside the device YAML so a
 * user can build and flash without remembering ESPHome invocations. Run it from
 * the unzipped bundle:  `bash compile.sh`  (or `compile|flash|upload|logs`).
 */
function generateCompileScript(dir: string): string {
  const device = `${dir}.yaml`;
  return [
    `#!/usr/bin/env bash`,
    `# Generated by MajiFlow — build & flash this device's ESPHome firmware.`,
    `# Usage: bash compile.sh [compile|flash|upload|logs]   (default: compile)`,
    `set -euo pipefail`,
    `cd "$(dirname "$0")"`,
    ``,
    `# ESP-IDF / PlatformIO refuse to build from a path containing a space.`,
    `# Catch it here with a clear message instead of a cryptic toolchain error`,
    `# (a common cause: the browser saved a duplicate download as "name (2)").`,
    `if printf '%s' "$PWD" | grep -q '[[:space:]]'; then`,
    `  echo "ERROR: this firmware folder sits in a path that contains a space:" >&2`,
    `  echo "  $PWD" >&2`,
    `  echo "ESP-IDF cannot build there. Move it to a path with no spaces and re-run, e.g.:" >&2`,
    `  echo "  mv THIS_FOLDER ~/majiflow-firmware && cd ~/majiflow-firmware && bash compile.sh" >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `DEVICE="${device}"`,
    ``,
    `if ! command -v esphome >/dev/null 2>&1; then`,
    `  echo "esphome not found. Install it with:  pip install esphome" >&2`,
    `  echo "(see https://esphome.io/guides/installing_esphome )" >&2`,
    `  exit 1`,
    `fi`,
    ``,
    `cmd="\${1:-compile}"`,
    `case "$cmd" in`,
    `  compile) esphome compile "$DEVICE" ;;        # build the firmware binary`,
    `  flash)   esphome run "$DEVICE" ;;            # build + upload (USB or OTA)`,
    `  upload)  esphome upload "$DEVICE" ;;         # upload an existing build`,
    `  logs)    esphome logs "$DEVICE" ;;           # tail device logs`,
    `  *) echo "usage: bash compile.sh [compile|flash|upload|logs]" >&2; exit 2 ;;`,
    `esac`,
    ``,
  ].join("\n");
}

/**
 * Generate firmware files for a manifest + board using the specified backend.
 */
export function generateFirmware(
  generator: GeneratorId,
  manifest: Manifest,
  board: BoardDef,
  siteId: string,
  secrets: SecretsMap | undefined,
  metadata: GenerationMetadata,
  expansionBoards: ExpansionBoardCatalog,
): GeneratedFile[] {
  if (generator === 'esphome') {
    return generateEsphome(manifest, board, siteId, secrets, metadata, expansionBoards);
  }
  throw new Error(`Unknown generator: ${generator}`);
}

export function generateAll(
  m: Manifest,
  board: BoardDef,
  siteId: string,
  secrets: SecretsMap | undefined,
  metadata: GenerationMetadata,
  expansionBoards: ExpansionBoardCatalog,
): GeneratedFile[] {
  return [...generateFirmware('esphome', m, board, siteId, secrets, metadata, expansionBoards)];
}
