# Home Assistant Configuration
# See: https://www.home-assistant.io/docs/configuration/

homeassistant:
  packages:
    pump_control: !include packages/pump_control.yaml

lovelace:
  mode: yaml
  dashboards:
    pump-dashboard:
      mode: yaml
      title: Water System
      icon: mdi:water-pump
      show_in_sidebar: true
      filename: dashboards/pump.yaml
