//go:build stm32wlx && !farmon_all

package main

// Empty registerDrivers — device-specific drivers are generated by the
// backend firmware builder and injected as generated_drivers.go.
func registerDrivers() {}
