import * as crypto from "node:crypto";
import type { Manifest } from "./schema.js";
import type { BoardDef } from "./board.js";
import { generateRoutes } from "./generators/routes.js";
import { generateHardware } from "./generators/hardware.js";
import { generateSensors } from "./generators/sensors.js";
import { generateDashboard } from "./generators/dashboard.js";
import { generateBoardPackage } from "./generators/board-package.js";
import { generateSiteDashboard, type SiteDashboardSystem } from "./generators/site-dashboard.js";
import { generateDeviceYaml } from "./generators/device-yaml.js";
import { generateControl } from "./generators/control.js";
import { generateAutomations } from "./generators/automations.js";
import { collectEntityCodegen } from "./generators/collect.js";
import { LOGO_SVG } from '@far-mon/core';

export interface GeneratedFile {
  relativePath: string;
  description: string;
  content: string;
}

export interface SecretsMap {
  wifi_ssid: string;
  wifi_password: string;
  api_key: string;
  ota_password: string;
}

export function generateDefaultSecrets(): SecretsMap {
  return {
    wifi_ssid: '',
    wifi_password: '',
    api_key: crypto.randomBytes(32).toString("base64"),
    ota_password: crypto.randomBytes(16).toString("hex"),
  };
}

function generateSecretsYaml(m: Manifest, secrets?: SecretsMap): string {
  const s = secrets ?? generateDefaultSecrets();
  return [
    `# ESPHome secrets for ${m.device.friendly_name}`,
    `# Generated by MajiFlow`,
    ``,
    `wifi_ssid: "${s.wifi_ssid}"`,
    `wifi_password: "${s.wifi_password}"`,
    `api_key: "${s.api_key}"`,
    `ota_password: "${s.ota_password}"`,
    ``,
  ].join("\n");
}

export function generateEsphome(m: Manifest, board: BoardDef, secrets?: SecretsMap): GeneratedFile[] {
  const dir = m.device.directory ?? m.device.name;
  const deviceDir = `esphome/${dir}`;
  const collected = collectEntityCodegen(m, board);

  return [
    {
      relativePath: `${deviceDir}/common/board.yaml`,
      description: `${board.label} board package (buses, battery, LED, diagnostics)`,
      content: generateBoardPackage(board, m.device.network),
    },
    {
      relativePath: `${deviceDir}/common/images/logo.svg`,
      description: "Logo image for OLED splash screen",
      content: LOGO_SVG,
    },
    {
      relativePath: `${deviceDir}/${dir}.yaml`,
      description: "Device config (substitutions, boot, OLED display)",
      content: generateDeviceYaml(board, m, collected),
    },
    {
      relativePath: `${deviceDir}/secrets.yaml`,
      description: "WiFi + API credentials",
      content: generateSecretsYaml(m, secrets),
    },
    {
      relativePath: `${deviceDir}/packages/control.yaml`,
      description: "State machine, API services, safety watchdog",
      content: generateControl(m),
    },
    {
      relativePath: `${deviceDir}/packages/routes.h`,
      description: "C++ route table + dispatch functions",
      content: generateRoutes(m),
    },
    {
      relativePath: `${deviceDir}/packages/hardware.yaml`,
      description: "Pump relay, valve switches + covers",
      content: generateHardware(m, collected),
    },
    {
      relativePath: `${deviceDir}/packages/sensors.yaml`,
      description: "Flow sensors, tank levels, calibration, state text",
      content: generateSensors(m, collected),
    },
  ];
}

export function generateSiteHA(
  siteName: string,
  systems: SiteDashboardSystem[],
  manifests: Map<string, Manifest>,
): GeneratedFile[] {
  const files: GeneratedFile[] = [
    {
      relativePath: `config/homeassistant/dashboards/site.yaml`,
      description: `HA dashboard — ${systems.length} controllers (overview + per-device tabs)`,
      content: generateSiteDashboard(siteName, systems),
    },
  ];

  for (const s of systems) {
    const m = manifests.get(s.systemId) ?? s.manifest;
    const dir = m.device.directory ?? m.device.name;
    const automationsContent = generateAutomations(m);
    if (automationsContent) {
      files.push({
        relativePath: `config/homeassistant/automations/${dir}.yaml`,
        description: `HA automations — ${s.friendlyName}`,
        content: automationsContent,
      });
    }
  }

  return files;
}

/** Legacy single-system convenience for tests. Produces ESPHome + per-device HA files. */
export function generateAll(m: Manifest, board: BoardDef, secrets?: SecretsMap): GeneratedFile[] {
  const dir = m.device.directory ?? m.device.name;
  const files = [...generateEsphome(m, board, secrets)];

  files.push({
    relativePath: `config/homeassistant/dashboards/dashboard.yaml`,
    description: "HA dashboard with gauges, controls, settings",
    content: generateDashboard(m),
  });

  const automationsContent = generateAutomations(m);
  if (automationsContent) {
    files.push({
      relativePath: `config/homeassistant/automations/${dir}.yaml`,
      description: "HA automations + system notifications",
      content: automationsContent,
    });
  }

  return files;
}
