import * as crypto from "node:crypto";
import type { Manifest } from "./schema.js";
import type { BoardDef } from "./board.js";
import type { Topology } from "./topology.js";
import { generateRoutes } from "./generators/routes.js";
import { generateHardware } from "./generators/hardware.js";
import { generateSensors } from "./generators/sensors.js";
import { generateDashboard } from "./generators/dashboard.js";
import { generateBoardPackage } from "./generators/board-package.js";
import { generateDeviceYaml } from "./generators/device-yaml.js";
import { generateControl } from "./generators/control.js";
import { generateAutomations } from "./generators/automations.js";
import { generateDocumentation } from "./generators/readme.js";
import { generateTopologySvg } from "./generators/topology-svg.js";
import { LOGO_SVG } from "./static/logo.js";

export interface GeneratedFile {
  relativePath: string;
  description: string;
  content: string;
}

function generateSecrets(m: Manifest): string {
  const apiKey = crypto.randomBytes(32).toString("base64");
  const otaPassword = crypto.randomBytes(16).toString("hex");
  return [
    `# ESPHome secrets for ${m.device.friendly_name}`,
    `# Generated by MajiFlow — edit with your actual credentials`,
    ``,
    `wifi_ssid: "YOUR_WIFI_SSID"`,
    `wifi_password: "YOUR_WIFI_PASSWORD"`,
    `fallback_password: "${otaPassword}"`,
    `api_key: "${apiKey}"`,
    `ota_password: "${otaPassword}"`,
    ``,
  ].join("\n");
}

export function generateAll(m: Manifest, board: BoardDef, topology?: Topology, canvasSvg?: string): GeneratedFile[] {
  const dir = m.device.directory ?? m.device.name;
  const deviceDir = `esphome/${dir}`;

  const files: GeneratedFile[] = [
    {
      relativePath: `${deviceDir}/common/board.yaml`,
      description: `${board.label} board package (buses, battery, LED, diagnostics)`,
      content: generateBoardPackage(board),
    },
    {
      relativePath: `${deviceDir}/common/images/logo.svg`,
      description: "Logo image for OLED splash screen",
      content: LOGO_SVG,
    },
    {
      relativePath: `${deviceDir}/${dir}.yaml`,
      description: "Device config (substitutions, boot, OLED display)",
      content: generateDeviceYaml(board, m),
    },
    {
      relativePath: `${deviceDir}/secrets.yaml`,
      description: "WiFi + API credentials (edit before flashing)",
      content: generateSecrets(m),
    },
    {
      relativePath: `${deviceDir}/packages/control.yaml`,
      description: "State machine, API services, safety watchdog",
      content: generateControl(m),
    },
    {
      relativePath: `${deviceDir}/packages/routes.h`,
      description: "C++ route table + dispatch functions",
      content: generateRoutes(m),
    },
    {
      relativePath: `${deviceDir}/packages/hardware.yaml`,
      description: "Pump relay, valve switches + covers",
      content: generateHardware(m),
    },
    {
      relativePath: `${deviceDir}/packages/sensors.yaml`,
      description: "Flow sensors, tank levels, calibration, state text",
      content: generateSensors(m),
    },
    {
      relativePath: `config/homeassistant/dashboards/dashboard.yaml`,
      description: "HA dashboard with gauges, controls, settings",
      content: generateDashboard(m),
    },
  ];

  // Conditionally add HA automations
  const automationsContent = generateAutomations(m);
  if (automationsContent) {
    files.push({
      relativePath: `config/homeassistant/automations/${dir}.yaml`,
      description: "HA automations + system notifications",
      content: automationsContent,
    });
  }

  // System documentation (HTML with embedded topology SVG)
  const topologySvg = canvasSvg || (topology ? generateTopologySvg(topology) : '');
  if (topologySvg) {
    files.push({
      relativePath: `${deviceDir}/documentation.html`,
      description: "System documentation (print to PDF from browser)",
      content: generateDocumentation(m, topologySvg),
    });
  }

  return files;
}
