import * as crypto from "node:crypto";
import type { Manifest } from "./schema.js";
import type { BoardDef } from "./board.js";
import { generateRoutes } from "./generators/routes.js";
import { generateHardware } from "./generators/hardware.js";
import { generateSensors } from "./generators/sensors.js";
import { generateDashboard } from "./generators/dashboard.js";
import { generateBoardPackage } from "./generators/board-package.js";
import { generateSiteDashboard, type SiteDashboardSystem } from "./generators/site-dashboard.js";
import { generateDeviceYaml } from "./generators/device-yaml.js";
import { generateControl } from "./generators/control.js";
import { generateAutomations } from "./generators/automations.js";

import { collectEntityCodegen } from "./generators/collect.js";
import { LOGO_SVG } from '@far-mon/core';
import { type GeneratorId, type SecretsMap, type GenerationMetadata } from './backends/types.js';

export interface GeneratedFile {
  relativePath: string;
  description: string;
  content: string;
}

export { type GeneratorId, type SecretsMap, type GenerationMetadata } from './backends/types.js';

/** Convenience helper for tests — creates a valid GenerationMetadata with defaults. */
export function createTestMetadata(overrides?: Partial<GenerationMetadata>): GenerationMetadata {
  return {
    configSha: 'testsha000000000',
    version: 'testver1',
    siteId: 'test-site',
    controllerId: 'default',
    schemaVersion: 16,
    buildTimestamp: 0,
    appVersion: '0.0.0',
    ...overrides,
  };
}

export function generateDefaultSecrets(): SecretsMap {
  return {
    wifi_ssid: '',
    wifi_password: '',
    api_key: crypto.randomBytes(32).toString("base64"),
    ota_password: crypto.randomBytes(16).toString("hex"),
  };
}

function generateSecretsYaml(m: Manifest, secrets?: SecretsMap): string {
  const s = secrets ?? generateDefaultSecrets();
  return [
    `# ESPHome secrets for ${m.device.friendly_name}`,
    `# Generated by MajiFlow`,
    ``,
    `wifi_ssid: "${s.wifi_ssid}"`,
    `wifi_password: "${s.wifi_password}"`,
    `api_key: "${s.api_key}"`,
    `ota_password: "${s.ota_password}"`,
    ``,
  ].join("\n");
}

function generateMetadataYaml(m: Manifest, metadata: GenerationMetadata): string {

  const lines: string[] = [];
  lines.push(`# =============================================================================`);
  lines.push(`# MajiFlow — Fleet Metadata Sensors`);
  lines.push(`# =============================================================================`);
  lines.push(`# Embedded provenance for drift detection and fleet management.`);
  lines.push(`# These sensors publish to Home Assistant as diagnostic entities.`);
  lines.push(`# =============================================================================`);
  lines.push(``);

  // text_sensor block
  lines.push(`text_sensor:`);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_config_sha`);
  lines.push(`    name: "MajiFlow Config SHA"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.configSha}";`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_generation_version`);
  lines.push(`    name: "MajiFlow Generation"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.version}";`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_site_id`);
  lines.push(`    name: "MajiFlow Site"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.siteId}";`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_controller_id`);
  lines.push(`    name: "MajiFlow Controller"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${metadata.controllerId}";`);
  lines.push(``);

  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_device_name`);
  lines.push(`    name: "MajiFlow Device Name"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return "${m.device.name}";`);
  lines.push(``);

  // sensor block
  lines.push(`sensor:`);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_build_timestamp`);
  lines.push(`    name: "MajiFlow Build Time"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    unit_of_measurement: "timestamp"`);
  lines.push(`    lambda: return ${metadata.buildTimestamp};`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_schema_version`);
  lines.push(`    name: "MajiFlow Schema"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return ${metadata.schemaVersion};`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_route_count`);
  lines.push(`    name: "MajiFlow Routes"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return ${m.routes.length};`);
  lines.push(``);
  lines.push(`  - platform: template`);
  lines.push(`    id: majiflow_node_count`);
  lines.push(`    name: "MajiFlow Nodes"`);
  lines.push(`    entity_category: diagnostic`);
  lines.push(`    lambda: return ${m.nodes.length};`);
  lines.push(``);

  return lines.join("\n");
}

/**
 * Returns the relative path prefix for everything a site generates.
 * `sites/{siteId}/...` is the single root for site-scoped artifacts:
 *   - `esphome/{deviceDir}/...`     — ESPHome firmware
 *   - `homeassistant/dashboards/{siteId}.yaml`        — site dashboard
 *   - `homeassistant/dashboards/dashboard.yaml`       — single-system convenience (tests)
 *   - `homeassistant/automations/{deviceDir}.yaml`    — per-device automations
 *   - `homeassistant/www/farm/{name}.{svg,meta.json}` — SCADA artifacts
 *   - `site-documentation.html`                       — generated docs
 *
 * Self-test artifacts live in a separate `selftest/{model}/` tree and bypass
 * this prefix entirely — they are not site-scoped.
 */
export function siteRoot(siteId: string): string {
  return `sites/${siteId}`;
}

export function generateEsphome(
  m: Manifest,
  board: BoardDef,
  siteId: string,
  secrets: SecretsMap | undefined,
  metadata: GenerationMetadata,
): GeneratedFile[] {
  const dir = m.device.directory ?? m.device.name;
  const deviceDir = `${siteRoot(siteId)}/esphome/${dir}`;
  const collected = collectEntityCodegen(m, board);

  const files: GeneratedFile[] = [
    {
      relativePath: `${deviceDir}/common/board.yaml`,
      description: `${board.label} board package (buses, battery, LED, diagnostics)`,
      content: generateBoardPackage(board, m.device.network),
    },
    {
      relativePath: `${deviceDir}/common/images/logo.svg`,
      description: "Logo image for OLED splash screen",
      content: LOGO_SVG,
    },
    {
      relativePath: `${deviceDir}/${dir}.yaml`,
      description: "Device config (substitutions, boot, OLED display)",
      content: generateDeviceYaml(board, m, collected, metadata),
    },
    {
      relativePath: `${deviceDir}/secrets.yaml`,
      description: "WiFi + API credentials",
      content: generateSecretsYaml(m, secrets),
    },
    {
      relativePath: `${deviceDir}/packages/control.yaml`,
      description: "State machine, API services, safety watchdog",
      content: generateControl(m),
    },
    {
      relativePath: `${deviceDir}/packages/routes.h`,
      description: "C++ route table + dispatch functions",
      content: generateRoutes(m),
    },
    {
      relativePath: `${deviceDir}/packages/hardware.yaml`,
      description: "Pump relay, valve switches + covers",
      content: generateHardware(m, collected),
    },
    {
      relativePath: `${deviceDir}/packages/sensors.yaml`,
      description: "Flow sensors, tank levels, calibration, state text",
      content: generateSensors(m, collected),
    },
    {
      relativePath: `${deviceDir}/packages/metadata.yaml`,
      description: "Fleet metadata sensors (SHA, version, build timestamp)",
      content: generateMetadataYaml(m, metadata),
    },
  ];

  return files;
}

export function generateSiteHA(
  siteId: string,
  siteName: string,
  systems: SiteDashboardSystem[],
  manifests: Map<string, Manifest>,
): GeneratedFile[] {
  const haRoot = `${siteRoot(siteId)}/homeassistant`;
  const files: GeneratedFile[] = [
    {
      relativePath: `${haRoot}/dashboards/${siteId}.yaml`,
      description: `HA dashboard — ${systems.length} controllers (overview + per-device tabs)`,
      content: generateSiteDashboard(siteName, systems),
    },
  ];

  for (const s of systems) {
    const m = manifests.get(s.systemId) ?? s.manifest;
    const dir = m.device.directory ?? m.device.name;
    const automationsContent = generateAutomations(m);
    if (automationsContent) {
      files.push({
        relativePath: `${haRoot}/automations/${dir}.yaml`,
        description: `HA automations — ${s.friendlyName}`,
        content: automationsContent,
      });
    }
  }

  return files;
}

/** Single-system convenience for tests. Produces ESPHome + per-device HA files. */
/**
 * Generate firmware files for a manifest + board using the specified backend.
 */
export function generateFirmware(
  generator: GeneratorId,
  manifest: Manifest,
  board: BoardDef,
  siteId: string,
  secrets: SecretsMap | undefined,
  metadata: GenerationMetadata,
): GeneratedFile[] {
  if (generator === 'esphome') {
    return generateEsphome(manifest, board, siteId, secrets, metadata);
  }
  throw new Error(`Unknown generator: ${generator}`);
}

export function generateAll(
  m: Manifest,
  board: BoardDef,
  siteId: string,
  secrets: SecretsMap | undefined,
  metadata: GenerationMetadata,
): GeneratedFile[] {
  const dir = m.device.directory ?? m.device.name;
  const haRoot = `${siteRoot(siteId)}/homeassistant`;
  const files = [...generateFirmware('esphome', m, board, siteId, secrets, metadata)];

  files.push({
    relativePath: `${haRoot}/dashboards/dashboard.yaml`,
    description: "HA dashboard with gauges, controls, settings",
    content: generateDashboard(m, board),
  });

  const automationsContent = generateAutomations(m);
  if (automationsContent) {
    files.push({
      relativePath: `${haRoot}/automations/${dir}.yaml`,
      description: "HA automations + system notifications",
      content: automationsContent,
    });
  }

  return files;
}
