#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Heltec Build Script
# =============================================================================
# Builds and uploads Arduino sketches for Heltec ESP32 LoRa V3
#
# Usage:
#   ./heltec.sh build <device_name> [sketch]   Build sketch (default: current dir)
#   ./heltec.sh upload [sketch] [port]          Upload to device
#   ./heltec.sh flash <device_name> [port]      Build and upload
#   ./heltec.sh monitor [port]                  Open serial monitor
#
# Environment:
#   LORAWAN_REGION   - US915, EU868, AU915, AS923 (default: US915)
#   LORAWAN_SUBBAND  - 1-8 for US915/AU915 (default: 2)

# --- Configuration ---
LORAWAN_REGION="${LORAWAN_REGION:-US915}"
LORAWAN_SUBBAND="${LORAWAN_SUBBAND:-2}"
# Use Espressif ESP32 package, not Heltec package
# The ropg library works with standard ESP32 board definitions
BOARD="esp32:esp32:heltec_wifi_lora_32_V3"
BAUD="115200"

# Build FQBN - Note: LoRaWanBand/SubBand options may not be available
# RadioLib handles region configuration in code, not via board options
FQBN="${BOARD}"

# Get script directory for relative path checks
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Find arduino-cli in multiple locations
find_arduino_cli() {
    # Check system PATH first
    if command -v arduino-cli &> /dev/null; then
        command -v arduino-cli
        return 0
    fi
    
    # Check local project bin directory
    if [ -f "$SCRIPT_DIR/bin/arduino-cli" ]; then
        echo "$SCRIPT_DIR/bin/arduino-cli"
        return 0
    fi
    
    # Check user bin directory
    if [ -f "$HOME/bin/arduino-cli" ]; then
        echo "$HOME/bin/arduino-cli"
        return 0
    fi
    
    return 1
}

# Find arduino-cli and set up PATH
ARDUINO_CLI=""
if ARDUINO_CLI=$(find_arduino_cli); then
    # Add directory to PATH if it's not already there
    ARDUINO_CLI_DIR=$(dirname "$ARDUINO_CLI")
    if [[ ":$PATH:" != *":$ARDUINO_CLI_DIR:"* ]]; then
        export PATH="$ARDUINO_CLI_DIR:$PATH"
    fi
else
    err "arduino-cli not found. Run ./setup_build_env.sh first to install it."
fi

# Verify arduino-cli is executable
if [ ! -x "$ARDUINO_CLI" ]; then
    err "arduino-cli found but not executable: $ARDUINO_CLI"
fi

# --- Helpers ---
log()  { echo -e "\033[0;36m→\033[0m $1"; }
ok()   { echo -e "\033[0;32m✓\033[0m $1"; }
err()  { echo -e "\033[0;31m✗\033[0m $1" >&2; exit 1; }

get_port() {
    local port="${1:-}"
    if [[ -n "$port" ]]; then
        echo "$port"
    else
        # Match both Linux (/dev/ttyUSB*, /dev/ttyACM*) and macOS (/dev/cu.*, /dev/tty.*) serial ports
        "$ARDUINO_CLI" board list 2>/dev/null | awk '/USB|ACM|cu\.|tty\./{print $1; exit}'
    fi
}

validate_device() {
    local device_name="$1"
    [[ -z "$device_name" ]] && err "Device name required. Usage: $0 {build|flash} <device_name> [args...]"
    
    local device_config="$SCRIPT_DIR/devices/$device_name/device_config.h"
    if [[ ! -f "$device_config" ]]; then
        err "Device '$device_name' not found. Expected: $device_config"
    fi
}

# --- Commands ---
cmd_build() {
    local device_name="${1:-}"
    validate_device "$device_name"
    
    local sketch="${2:-.}"
    [[ -d "$sketch" ]] || err "Sketch directory not found: $sketch"
    
    # Generate device config include file (must be first to avoid duplicate includes)
    local include_file="$sketch/device_config_include.h"
    echo "#pragma once" > "$include_file"
    echo "// Auto-generated by heltec.sh - do not edit" >> "$include_file"
    echo "#include \"devices/$device_name/device_config.h\"" >> "$include_file"
    
    log "Building $sketch for device '$device_name' (${LORAWAN_REGION}, sub-band ${LORAWAN_SUBBAND})..."
    "$ARDUINO_CLI" compile --fqbn "$FQBN" "$sketch"
    
    # Clean up generated file
    rm -f "$include_file"
    
    ok "Build complete"
}

cmd_upload() {
    local sketch="${1:-.}"
    local port=$(get_port "${2:-}")
    [[ -n "$port" ]] || err "No board found. Connect device or specify port."
    
    log "Uploading $sketch to $port..."
    "$ARDUINO_CLI" upload -p "$port" --fqbn "$FQBN" "$sketch"
    ok "Upload complete"
}

cmd_flash() {
    local device_name="${1:-}"
    validate_device "$device_name"
    
    local port="${2:-}"
    local sketch="."
    
    cmd_build "$device_name" "$sketch"
    cmd_upload "$sketch" "$port"
}

cmd_monitor() {
    local port=$(get_port "${1:-}")
    [[ -n "$port" ]] || err "No board found. Connect device or specify port."
    
    log "Opening serial monitor on $port at ${BAUD} baud..."
    log "Press Ctrl+C to exit"
    "$ARDUINO_CLI" monitor -p "$port" -c baudrate=$BAUD
}

# --- Main ---
ACTION="${1:-}"
shift || true

case "$ACTION" in
    build)   cmd_build "$@" ;;
    upload)  cmd_upload "$@" ;;
    flash)   cmd_flash "$@" ;;
    monitor) cmd_monitor "$@" ;;
    *)
        echo "Usage: $0 {build|upload|flash|monitor} [args...]"
        echo ""
        echo "Commands:"
        echo "  build <device_name> [sketch]   Compile sketch for device"
        echo "  upload [sketch] [port]         Upload to device"
        echo "  flash <device_name> [port]      Build and upload for device"
        echo "  monitor [port]                 Serial monitor"
        echo ""
        echo "Examples:"
        echo "  $0 flash remote_03 /dev/ttyUSB0     # Linux"
        echo "  $0 flash remote_03 /dev/cu.usbserial # macOS"
        echo "  $0 build remote_03"
        echo ""
        echo "Environment:"
        echo "  LORAWAN_REGION=$LORAWAN_REGION"
        echo "  LORAWAN_SUBBAND=$LORAWAN_SUBBAND"
        exit 1
        ;;
esac
