import * as crypto from "node:crypto";
import type { Manifest } from "./schema.js";
import type { BoardDef } from "./board.js";
import { generateRoutes } from "./generators/routes.js";
import { generateHardware } from "./generators/hardware.js";
import { generateSensors } from "./generators/sensors.js";
import { generateDashboard } from "./generators/dashboard.js";
import { generateBoardPackage } from "./generators/board-package.js";
import { generateDeviceYaml } from "./generators/device-yaml.js";
import { CONTROL_YAML } from "./static/control.js";
import { LOGO_SVG } from "./static/logo.js";

export interface GeneratedFile {
  relativePath: string;
  description: string;
  content: string;
}

function generateSecrets(m: Manifest): string {
  const apiKey = crypto.randomBytes(32).toString("base64");
  const otaPassword = crypto.randomBytes(16).toString("hex");
  return [
    `# ESPHome secrets for ${m.device.friendly_name}`,
    `# Generated by waterctl — edit with your actual credentials`,
    ``,
    `wifi_ssid: "YOUR_WIFI_SSID"`,
    `wifi_password: "YOUR_WIFI_PASSWORD"`,
    `fallback_password: "${otaPassword}"`,
    `api_key: "${apiKey}"`,
    `ota_password: "${otaPassword}"`,
    ``,
  ].join("\n");
}

export function generateAll(m: Manifest, board: BoardDef): GeneratedFile[] {
  const dir = m.device.directory ?? m.device.name;
  const deviceDir = `esphome/${dir}`;

  return [
    {
      relativePath: `${deviceDir}/common/board.yaml`,
      description: `${board.label} board package (buses, battery, LED, diagnostics)`,
      content: generateBoardPackage(board),
    },
    {
      relativePath: `${deviceDir}/common/images/logo.svg`,
      description: "Logo image for OLED splash screen",
      content: LOGO_SVG,
    },
    {
      relativePath: `${deviceDir}/${dir}.yaml`,
      description: "Device config (substitutions, boot, OLED display)",
      content: generateDeviceYaml(board, m),
    },
    {
      relativePath: `${deviceDir}/secrets.yaml`,
      description: "WiFi + API credentials (edit before flashing)",
      content: generateSecrets(m),
    },
    {
      relativePath: `${deviceDir}/packages/control.yaml`,
      description: "State machine, API services, safety watchdog (static)",
      content: CONTROL_YAML,
    },
    {
      relativePath: `${deviceDir}/packages/routes.h`,
      description: "C++ route table + dispatch functions",
      content: generateRoutes(m),
    },
    {
      relativePath: `${deviceDir}/packages/hardware.yaml`,
      description: "Pump relay, valve switches + covers",
      content: generateHardware(m),
    },
    {
      relativePath: `${deviceDir}/packages/sensors.yaml`,
      description: "Flow sensors, tank levels, calibration, state text",
      content: generateSensors(m),
    },
    {
      relativePath: `config/homeassistant/dashboards/pump.yaml`,
      description: "HA dashboard with gauges, controls, settings",
      content: generateDashboard(m),
    },
  ];
}
