import { stringify } from "yaml";
import type { Manifest, ManifestNode } from "../schema.js";
import { nodesWithFlag } from "../schema.js";
import { NODE_REGISTRY, systemHaEntityIds, routeAutomationAlias, findRouteAutomationSensor, type TankLevelSource } from '@far-mon/core';

function haIds(node: ManifestNode, device: { friendly_name: string }): Record<string, string | undefined> {
  return NODE_REGISTRY.get(node.kind)?.codegen?.haEntityIds?.(node, device) ?? {};
}

/**
 * Generate Home Assistant automation YAML — user-configured schedule automations
 * plus system-generated notifications (fault alerts, water critical).
 *
 * Actions use per-route button entities (button.press) — these go through
 * the ESP32 state machine, so all safety logic is preserved.
 *
 * Returns null only when no automations of any kind are applicable.
 */
export function generateAutomations(m: Manifest): string | null {
  const levelSensors = nodesWithFlag(m.nodes, 'isLevelSensor');
  const sys = systemHaEntityIds(m.device, m.routes);

  // Build the tank → level source lookup the helper expects, reading from
  // tank annotations attached during topologyToManifest.
  const tankLevelSourceById = new Map<string, TankLevelSource>();
  const nodeKindById = new Map<string, string>();
  for (const n of m.nodes) {
    nodeKindById.set(n['id'] as string, n.kind);
    if (n.kind === 'tank' && n['level_source']) {
      tankLevelSourceById.set(n['id'] as string, n['level_source'] as TankLevelSource);
    }
  }

  const automations = m.automations
    .filter(a => a.name && a.route_key && a.route_index >= 0 && a.route_index < m.routes.length)
    .map((a) => {
    const startButton = sys.routes[a.route_index].start;

    // Build trigger
    const trigger: Record<string, unknown>[] = [];
    if (a.trigger.type === "time") {
      trigger.push({
        trigger: "time",
        at: `${a.trigger.at}:00`,
      });
    } else if (a.trigger.type === "level") {
      const route = m.routes[a.route_index];
      const found = findRouteAutomationSensor(route, tankLevelSourceById, nodeKindById);
      if (!found) {
        throw new Error(`Automation "${a.name}" uses a level trigger, but route "${route.name}" has no source tank with a level sensor positioned before its first valve/pump. Change the trigger to time-based, or add a level sensor to the source tank.`);
      }
      if (!route.source_min_pct) {
        throw new Error(`Automation "${a.name}" uses a level trigger, but route "${route.name}" has no Source Min Level set. The trigger fires when the source tank rises above this value, so it must be > 0.`);
      }
      const sensorNode = m.nodes.find(n => n['id'] === found.sensorId);
      const entityId = sensorNode ? haIds(sensorNode, m.device).level : undefined;
      if (!entityId) {
        throw new Error(`Automation "${a.name}": resolved sensor "${found.sensorId}" exposes no level entity_id.`);
      }

      const levelTrigger: Record<string, unknown> = {
        trigger: "numeric_state",
        entity_id: entityId,
        above: route.source_min_pct,
      };
      if (a.trigger.for_minutes) {
        const mins = Math.floor(a.trigger.for_minutes);
        levelTrigger.for = `00:${String(mins).padStart(2, '0')}:00`;
      }
      trigger.push(levelTrigger);
    }

    // Build conditions
    const condition: Record<string, unknown>[] = [];

    // Day-of-week filter (only if not all 7 days)
    if (a.days_of_week.length < 7) {
      condition.push({
        condition: "time",
        weekday: a.days_of_week.map(d => d.toLowerCase().slice(0, 3)),
      });
    }

    // Source/dest level checks are firmware-enforced via route_overrides
    // (source_min_pct / dest_max_pct in the C++ Route struct).
    // The HA automation just decides *when* to attempt a start;
    // firmware decides *whether* it's safe.

    return {
      alias: routeAutomationAlias(a),
      description: "Auto-generated by MajiFlow — edit freely in HA",
      triggers: trigger,
      conditions: condition,
      actions: [
        {
          action: "button.press",
          target: { entity_id: startButton },
        },
      ],
      mode: "single",
    };
  });

  // --- System notification automations (always generated when applicable) ---

  const systemAutomations: Record<string, unknown>[] = [];

  // Fault alert — every system with routes
  if (m.routes.length > 0) {
    systemAutomations.push({
      alias: "System Fault Alert",
      description: "Auto-generated by MajiFlow — notifies on any route fault",
      triggers: [{ trigger: "state", entity_id: sys.systemState, to: "FAULT" }],
      conditions: [],
      actions: [{
        action: "persistent_notification.create",
        data: {
          title: "WATER SYSTEM FAULT",
          message: `{{ states('${sys.systemFault}') }}`,
        },
      }],
      mode: "single",
    });
  }

  // Water critical — when 2+ level sensors
  if (levelSensors.length >= 2) {
    const levelMessages = levelSensors.map(ls =>
      `${ls['name']}: {{ states('${haIds(ls, m.device).level}') }}%`
    ).join(", ");
    systemAutomations.push({
      alias: "Water Critical Alert",
      description: "Auto-generated by MajiFlow — notifies when combined level is critically low",
      triggers: [{ trigger: "state", entity_id: sys.waterCritical, to: "on", for: "00:05:00" }],
      conditions: [],
      actions: [{
        action: "persistent_notification.create",
        data: {
          title: "WATER LEVEL CRITICAL",
          message: levelMessages,
        },
      }],
      mode: "single",
    });
  }

  if (automations.length === 0 && systemAutomations.length === 0) return null;

  const yamlOpts = {
    indent: 2,
    lineWidth: 0,
    defaultStringType: "PLAIN" as const,
    defaultKeyType: "PLAIN" as const,
  };

  const sections: string[] = [];

  if (automations.length > 0) {
    sections.push(
      [
        "# ===== Schedule Automations =====",
        "# For each automation below:",
        "#   1. Go to Settings → Automations & Scenes → + Create Automation",
        '#   2. Click ⋮ (three dots, top-right) → Edit in YAML',
        "#   3. Select all, paste the block (one per automation), then Save",
      ].join("\n"),
      ...automations.map(a => stringify(a, yamlOpts).trimEnd()),
    );
  }

  if (systemAutomations.length > 0) {
    sections.push(
      [
        "# ===== System Alerts =====",
        "# Import these the same way. These fire HA notifications",
        "# when faults or critical water levels are detected.",
      ].join("\n"),
      ...systemAutomations.map(a => stringify(a, yamlOpts).trimEnd()),
    );
  }

  return sections.join("\n\n---\n\n") + "\n";
}
