import { stringify } from "yaml";
import type { Manifest, ManifestAutomation } from "../schema.js";
import { nodesByKind } from "../schema.js";

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
    .replace(/_+/g, "_");
}

function entityId(domain: string, deviceName: string, name: string): string {
  return `${domain}.${slug(deviceName)}_${slug(name)}`;
}

/**
 * Generate Home Assistant automation YAML for configured route automations.
 * Returns null when no automations are configured.
 *
 * Actions use per-route button entities (button.press) — these go through
 * the ESP32 state machine, so all safety logic is preserved.
 */
export function generateAutomations(m: Manifest): string | null {
  if (m.automations.length === 0) return null;

  const dev = slug(m.device.name);
  const tanks = nodesByKind(m.nodes, 'tank');
  const tankIdx = new Map(tanks.map((t, i) => [t['id'], i]));

  const automations = m.automations.map((a) => {
    const route = m.routes[a.route_index];
    const startButton = entityId("button", m.device.name, `Start ${route.name}`);

    // Build trigger
    const trigger: Record<string, unknown>[] = [];
    if (a.trigger.type === "time") {
      trigger.push({
        platform: "time",
        at: `${a.trigger.at}:00`,
      });
    } else if (a.trigger.type === "level") {
      const levelTrigger: Record<string, unknown> = {
        platform: "numeric_state",
        entity_id: a.trigger.entity,
      };
      if (a.trigger.below !== undefined) levelTrigger.below = a.trigger.below;
      if (a.trigger.above !== undefined) levelTrigger.above = a.trigger.above;
      trigger.push(levelTrigger);
    }

    // Build conditions
    const condition: Record<string, unknown>[] = [];

    // Day-of-week filter (only if not all 7 days)
    if (a.days_of_week.length < 7) {
      condition.push({
        condition: "time",
        weekday: a.days_of_week.map(d => d.toLowerCase().slice(0, 3)),
      });
    }

    // Source/dest level checks are firmware-enforced via route_overrides
    // (source_min_pct / dest_max_pct in the C++ Route struct).
    // The HA automation just decides *when* to attempt a start;
    // firmware decides *whether* it's safe.

    return {
      id: `majiflow_${a.id}`,
      alias: `${a.name}: ${a.route_name}`,
      description: "Auto-generated by MajiFlow — edit freely in HA",
      trigger,
      condition,
      action: [
        {
          service: "button.press",
          target: { entity_id: startButton },
        },
      ],
      mode: "single",
    };
  });

  return stringify(automations, {
    indent: 2,
    lineWidth: 0,
    defaultStringType: "PLAIN",
    defaultKeyType: "PLAIN",
  });
}
