import { stringify } from "yaml";
import type { Manifest, ManifestAutomation } from "../schema.js";
import { nodesByKind, slug } from "../schema.js";

function entityId(domain: string, deviceName: string, name: string): string {
  return `${domain}.${slug(deviceName)}_${slug(name)}`;
}

/**
 * Generate Home Assistant automation YAML — user-configured schedule automations
 * plus system-generated notifications (fault alerts, water critical).
 *
 * Actions use per-route button entities (button.press) — these go through
 * the ESP32 state machine, so all safety logic is preserved.
 *
 * Returns null only when no automations of any kind are applicable.
 */
export function generateAutomations(m: Manifest): string | null {
  const dev = slug(m.device.name);
  const tanks = nodesByKind(m.nodes, 'tank');
  const tanksWithLevel = tanks.filter(t => t['level_pin']);
  const tankIdx = new Map(tanks.map((t, i) => [t['id'], i]));

  const automations = m.automations
    .filter(a => a.name && a.route_key && a.route_index >= 0 && a.route_index < m.routes.length)
    .map((a) => {
    const route = m.routes[a.route_index];
    const startButton = entityId("button", m.device.name, `Start ${route.name}`);

    // Build trigger
    const trigger: Record<string, unknown>[] = [];
    if (a.trigger.type === "time") {
      trigger.push({
        platform: "time",
        at: `${a.trigger.at}:00`,
      });
    } else if (a.trigger.type === "level") {
      const lt = a.trigger;
      // Resolve node reference to HA entity ID, or use raw entity as fallback
      let resolvedEntity: string;
      if (lt.node) {
        const node = m.nodes.find(n => n['id'] === lt.node);
        const nodeName = node ? String(node['name']) : lt.node;
        resolvedEntity = entityId("sensor", m.device.name, `${nodeName} Level`);
      } else if (lt.entity) {
        resolvedEntity = lt.entity;
      } else {
        resolvedEntity = "";
      }

      const levelTrigger: Record<string, unknown> = {
        platform: "numeric_state",
        entity_id: resolvedEntity,
      };
      if (lt.below !== undefined) levelTrigger.below = lt.below;
      if (lt.above !== undefined) levelTrigger.above = lt.above;
      if (lt.for_minutes) {
        const mins = Math.floor(lt.for_minutes);
        levelTrigger.for = `00:${String(mins).padStart(2, '0')}:00`;
      }
      trigger.push(levelTrigger);
    }

    // Build conditions
    const condition: Record<string, unknown>[] = [];

    // Day-of-week filter (only if not all 7 days)
    if (a.days_of_week.length < 7) {
      condition.push({
        condition: "time",
        weekday: a.days_of_week.map(d => d.toLowerCase().slice(0, 3)),
      });
    }

    // Source/dest level checks are firmware-enforced via route_overrides
    // (source_min_pct / dest_max_pct in the C++ Route struct).
    // The HA automation just decides *when* to attempt a start;
    // firmware decides *whether* it's safe.

    return {
      id: `majiflow_${a.id}`,
      alias: `${a.name}: ${a.route_name}`,
      description: "Auto-generated by MajiFlow — edit freely in HA",
      trigger,
      condition,
      action: [
        {
          service: "button.press",
          target: { entity_id: startButton },
        },
      ],
      mode: "single",
    };
  });

  // --- System notification automations (always generated when applicable) ---

  const systemAutomations: Record<string, unknown>[] = [];

  // Fault alert — every system with routes
  if (m.routes.length > 0) {
    const stateSensor = entityId("sensor", m.device.name, "System State");
    const faultSensor = entityId("sensor", m.device.name, "System Fault");
    systemAutomations.push({
      id: "majiflow_fault_alert",
      alias: "System Fault Alert",
      description: "Auto-generated by MajiFlow — notifies on any route fault",
      trigger: [{ platform: "state", entity_id: stateSensor, to: "FAULT" }],
      condition: [],
      action: [{
        service: "persistent_notification.create",
        data: {
          title: "WATER SYSTEM FAULT",
          message: `{{ states('${faultSensor}') }}`,
        },
      }],
      mode: "single",
    });
  }

  // Water critical — when 2+ tanks with level sensors
  if (tanksWithLevel.length >= 2) {
    const waterCritical = entityId("binary_sensor", m.device.name, "Water Critical");
    const levelMessages = tanksWithLevel.map(t =>
      `${t['name']}: {{ states('${entityId("sensor", m.device.name, `${t['name']} Level`)}') }}%`
    ).join(", ");
    systemAutomations.push({
      id: "majiflow_water_critical",
      alias: "Water Critical Alert",
      description: "Auto-generated by MajiFlow — notifies when combined level is critically low",
      trigger: [{ platform: "state", entity_id: waterCritical, to: "on", for: "00:05:00" }],
      condition: [],
      action: [{
        service: "persistent_notification.create",
        data: {
          title: "WATER LEVEL CRITICAL",
          message: levelMessages,
        },
      }],
      mode: "single",
    });
  }

  const allAutomations = [...automations, ...systemAutomations];
  if (allAutomations.length === 0) return null;

  return stringify(allAutomations, {
    indent: 2,
    lineWidth: 0,
    defaultStringType: "PLAIN",
    defaultKeyType: "PLAIN",
  });
}
