import type { Manifest } from "../schema.js";
import { nodesByKind } from "../schema.js";

export function generateReadme(m: Manifest): string {
  const tanks = nodesByKind(m.nodes, 'tank');
  const tanksWithLevel = tanks.filter(t => t['level_pin']);
  const pumps = nodesByKind(m.nodes, 'pump');
  const flowSensors = nodesByKind(m.nodes, 'flow_sensor');

  // Route table
  const routeRows = m.routes.map(r => {
    const srcMin = r.source_min_pct > 0 ? `min ${r.source_min_pct}%` : 'none';
    const dstMax = r.dest_max_pct > 0 ? `max ${r.dest_max_pct}%` : 'none';
    const safety = [srcMin !== 'none' ? `src ${srcMin}` : '', dstMax !== 'none' ? `dst ${dstMax}` : ''].filter(Boolean).join(', ') || 'defaults only';
    const runtime = r.max_runtime_seconds >= 3600
      ? `${(r.max_runtime_seconds / 3600).toFixed(1)}h`
      : `${r.max_runtime_seconds}s`;
    return `| ${r.name} | ${r.needs_pump ? 'pumped' : 'gravity'} | ${safety} | ${runtime} | ${r.runtime_level_ok ? 'yes' : 'no'} |`;
  });

  // Automation summary
  const autoLines = m.automations
    .filter(a => a.name && a.enabled)
    .map(a => {
      const trigger = a.trigger.type === 'time' ? `${a.trigger.at} daily` : 'level trigger';
      return `- **${a.name}**: ${trigger} → ${a.route_name}`;
    });

  // System alerts
  const alerts: string[] = ['- Fault alert on any route failure'];
  if (tanksWithLevel.length >= 2) {
    alerts.push('- Water critical when combined tank level < 35%');
  }

  // Installation notes from topology
  const installNotes: string[] = [];
  if (flowSensors.length > 0 && pumps.length > 0) {
    installNotes.push(
      '- **10D5D rule**: flow sensors need 10 pipe diameters downstream of pump, 5 upstream of next valve/fitting',
    );
  }
  for (const t of tanks) {
    if (!t['pump_rated'] && t['level_pin']) {
      installNotes.push(
        `- **${t['name']}**: level sensor not pump-rated — readings suppressed during pump operation. For runtime level monitoring, use a pressure transducer.`,
      );
    }
  }

  return `# ${m.device.friendly_name} — Water System

Generated by MajiFlow. Edit HA automations freely; firmware files are regenerated on deploy.

## Topology

- ${tanks.length} tank(s), ${pumps.length} pump(s), ${flowSensors.length} flow sensor(s)
- ${m.routes.length} route(s), max ${m.routes.filter(r => r.needs_pump).length} pumped

## Routes

| Route | Type | Level Guards | Max Runtime | Runtime Level |
|-------|------|-------------|-------------|---------------|
${routeRows.join('\n')}

## Automations (HA-managed, editable post-deploy)

${autoLines.length > 0 ? autoLines.join('\n') : '_No automations configured._'}

## System Alerts (auto-generated)

${alerts.join('\n')}

## Firmware Safety (ESP32-enforced)

- **Pre-start**: source/dest level checks reject unsafe starts (always, pump off)
- **Runtime**: flow watchdog (${m.timing.flow_watchdog_seconds}s), max runtime per route
- **Runtime level**: only on routes where sensors are pump-rated (see table above)
- **API watchdog**: faults route if HA disconnects for ${m.timing.api_watchdog_seconds}s

${installNotes.length > 0 ? `## Installation Notes\n\n${installNotes.join('\n')}\n` : ''}`;
}
