/**
 * Self-test firmware generator — public API.
 *
 * Imports all probes, filters by board, composes firmware files.
 * To add a test: create a new probe in probes/ and add it to ALL_PROBES below.
 */

import type { BoardDef } from '@far-mon/core';
import type { GeneratedFile, SecretsMap } from '../generate';
import { generateDefaultSecrets } from '../generate';
import type { NetworkConfig } from '@far-mon/core';
import type { TestProbe } from './probe';
import { generateBoardPackage } from '../generators/board-package';
import { generateSequencer } from './sequencer';
import { generateDeviceYaml } from './device-yaml';
import { generateDashboard } from './dashboard';

// --- Probe registry (add new probes here) ---
import { i2cScanProbe } from './probes/i2c-scan';
import { relayCycleProbe } from './probes/relay-cycle';
import { digitalInputsProbe } from './probes/digital-inputs';
import { adcBaselineProbe } from './probes/adc-baseline';
import { sensorHeadersProbe } from './probes/sensor-headers';
import { ethernetPhyProbe } from './probes/ethernet-phy';
import { oledDisplayProbe } from './probes/oled-display';
import { loraSpiProbe } from './probes/lora-spi';
import { wifiScanProbe } from './probes/wifi-scan';
import { batteryAdcProbe } from './probes/battery-adc';
import { ledBlinkProbe } from './probes/led-blink';
import { vextGateProbe } from './probes/vext-gate';

const ALL_PROBES: TestProbe[] = [
  i2cScanProbe,
  relayCycleProbe,
  digitalInputsProbe,
  adcBaselineProbe,
  sensorHeadersProbe,
  ethernetPhyProbe,
  oledDisplayProbe,
  loraSpiProbe,
  wifiScanProbe,
  batteryAdcProbe,
  ledBlinkProbe,
  vextGateProbe,
];

/** Filter probes to those applicable for a board. */
export function activeProbes(board: BoardDef): TestProbe[] {
  return ALL_PROBES.filter(p => p.appliesTo(board));
}

function generateSecrets(secrets?: SecretsMap): string {
  const s = secrets ?? generateDefaultSecrets();
  return [
    `# Self-test secrets`,
    `# Generated by MajiFlow`,
    ``,
    `wifi_ssid: "${s.wifi_ssid}"`,
    `wifi_password: "${s.wifi_password}"`,
    `api_key: "${s.api_key}"`,
    `ota_password: "${s.ota_password}"`,
    ``,
  ].join('\n');
}

/**
 * Generate all files for self-test firmware.
 *
 * Self-test artifacts live under `selftest/{model}/` — a sibling of the
 * site-scoped `sites/{siteId}/` tree. Self-test is per-board and not
 * site-scoped (it's an ad-hoc factory verification, not a deployable system).
 */
export function generateSelfTest(board: BoardDef, secrets?: SecretsMap, network?: NetworkConfig): GeneratedFile[] {
  const model = board.model.replace('_', '-');
  const dir = `selftest-${model}`;
  const root = `selftest/${model}`;
  const probes = activeProbes(board);

  return [
    {
      relativePath: `${root}/esphome/${dir}/common/board.yaml`,
      description: `${board.label} board package (buses, networking, diagnostics)`,
      content: generateBoardPackage(board, network),
    },
    {
      relativePath: `${root}/esphome/${dir}/${dir}.yaml`,
      description: `Self-test device config (${probes.length} probes)`,
      content: generateDeviceYaml(board, probes),
    },
    {
      relativePath: `${root}/esphome/${dir}/packages/self-test.h`,
      description: `C++ test sequencer (${probes.length} test phases)`,
      content: generateSequencer(board, probes),
    },
    {
      relativePath: `${root}/esphome/${dir}/secrets.yaml`,
      description: 'WiFi + API credentials',
      content: generateSecrets(secrets),
    },
    {
      relativePath: `${root}/homeassistant/dashboards/${dir}.yaml`,
      description: `HA dashboard for self-test results`,
      content: generateDashboard(board, probes),
    },
  ];
}
